name: Lint Server

on:
  workflow_call:

jobs:
  Builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Packages
        working-directory: server
        run: npm install

      - name: Build Server
        working-directory: server
        run: npm run build

      - name: Build Server
        working-directory: server
        run: tar -cvf build.tar dist/

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar
