name: Docker Build

on:
  pull_request:
  release:
    types: [published]
    
env:
  IMAGE_NAME: "@tkottke90/web-archive"

jobs:
  Builder:
    runs-on: ubuntu-latest
    outputs:
      img: ${{ steps.version.outputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Version
        id: version
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF: ${{ github.ref }}
          SHA: ${{ github.sha }}
        run: |
          if [[ $REF_TYPE == "tag" ]]; then
            VERSION=$(echo $REF | rev | cut -d '/' -f 1 | rev)
          else
            if [[ $REF == *release/* ]]; then
              VERSION=$(echo $REF | rev | cut -d '/' -f 1 | rev)-RC
            else
              VERSION=$(echo $SHA | cut -b 1-8)-DEV-SNAPSHOT
            fi
          fi

          IMAGE="${{ inputs.registry || 'ghcr.io' }}/${{ inputs.image_name || env.IMAGE_NAME }}"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE}:${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: ./.github/actions/npm-app-docker
        with:
          registry: ${{ inputs.registry || 'ghcr.io' }}
          image-tag: ${{ steps.version.outputs.image_tag }}
          push: ${{ inputs.deploy == true || github.event_name == 'release' }}
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}
          build-args: |
            COMMIT=${{ github.sha }}
            BRANCH=${{ github.ref }}
            VERSION=${{ steps.version.outputs.version }}
