name: Build Docker Image

on:
  workflow_call:
    inputs:
      registry:
        type: string
        default: ghcr.io
      image:
        type: string
        required: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: Deploy to ${{ inputs.registry }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download image
        uses: ishworkh/container-image-artifact-download@v1.0.0
        with:
          image: ${{ inputs.image }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ inputs.registry }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image  ${{ inputs.image }}
        env:
          IMAGE: ${{ inputs.image }}
        run: |
          docker push $IMAGE