name: CICD

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["release/*"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
    
jobs:
  Lint:
    name: Lint Server
    uses: ./.github/workflows/lint-server.yaml

  Build:
    uses: ./.github/workflows/build.yaml
    name: Build Image
    needs: [Lint]
    with:
      deploy: ${{ github.event_name != 'pull_request' }}
      target_dir: "server"
      

  Deploy:
    uses: ./.github/workflows/build-docker.yaml
    name: Deploy
    needs: [Build]
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      packages: write
    with:
      image: ${{ needs.build.outputs.image }}

  Release:
    name: Create Release
    needs: [Deploy]
    if: ${{ github.ref_type == 'tag' }}
    steps:
      - name: Temp
        run: echo "Release"