name: CICD

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["release/*"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
    
jobs:
  Lint:
    name: Lint Server
    uses: ./.github/workflows/lint-server.yaml

  Build:
    runs-on: [ ubuntu-latest ]
    needs: [Lint]
    outputs:
      image: ${{ steps.img_build.outputs.imgname }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup PAT
        working-directory: './ui'
        run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
      
      - name: Install Dependencies
        run: |
          (cd ui && npm ci)
          (cd server && npm ci)

      - name: Build UI
        working-directory: './ui'
        run: npm run build
      
      - name: Mv to public
        run: cp -r ./ui/dist/* ./server/public

      - name: Mv to public
        run: cp -r ./ui/package.json ./server/public

      - name: Build API
        working-directory: './server'
        run: npm run build

      - name: Get Version
        id: version
        working-directory: './server'
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF: ${{ github.ref }}
          SHA: ${{ github.sha }}
        run: |
          if [[ $REF_TYPE == "tag" ]]; then
            VERSION=$(echo $REF | rev | cut -d '/' -f 1 | rev)
          else
            if [[ $REF == *release/* ]]; then
              VERSION=$(echo $REF | rev | cut -d '/' -f 1 | rev)-RC
            else
              VERSION=$(echo $SHA | cut -b 1-8)-DEV-SNAPSHOT
            fi
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build Image
        id: img_build
        working-directory: './server'
        env:
          API_IMAGE: "ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}"
          VERSION: ${{ steps.version.outputs.version }}
          COMMIT: ${{ github.sha }}
          BRANCH: ${{ github.ref }}
          FILE: Dockerfile
        run: |
          echo "# Image Details" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "COMMIT: $COMMIT" >> $GITHUB_STEP_SUMMARY
          echo "BRANCH: $BRANCH" >> $GITHUB_STEP_SUMMARY
          
          docker build \
            -f $FILE \
            -t $API_IMAGE \
            --build-arg "COMMIT=$(git rev-parse HEAD)" \
            --build-arg "BRANCH=$(git rev-parse --abbrev-ref HEAD)"  \
            --build-arg "VERSION=$VERSION"  \
            .

          echo "imgname=$API_IMAGE" >> $GITHUB_OUTPUT
  
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Push to Github Packeges
        env:
          API_IMAGE: "ghcr.io/${{ steps.img_build.outputs.imgname }}:${{ steps.version.outputs.version }}"
        run: |
          docker push $API_IMAGE
