name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Increment'
        type: choice
        options:
        - Patch
        - Minor
        - Major
        default: 'Minor'

jobs:  
  release-candidate:
    name: Create Release Branch
    runs-on: ubuntu-latest
    if: ${{ endsWith(github.ref, 'main') }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Packages
        working-directory: server
        run: npm install

      - name: Bump Version - Patch
        if: ${{ inputs.version == 'Patch' }}
        working-directory: server
        run: |
          npm version patch
          npm run changelog-patch
      
      - name: Bump Version - Minor
        if: ${{ inputs.version == 'Minor' }}
        working-directory: server
        run: |
          npm version minor
          npm run changelog-minor
      
      - name: Bump Version - Major
        if: ${{ inputs.version == 'Major' }}
        working-directory: server
        run: |
          npm version major
          npm run changelog-major

      - name: Commit Changes
        working-directory: server
        env:
          AUTHOR: ${{ github.triggering_actor }}
        run: |
          VERSION=$(npm pkg get version | sed 's/\"//g')
          echo $VERSION
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "automation: Create Changelog for v$VERSION"
          git push

      - name: Create Release Branch
        working-directory: server
        run: |
          VERSION=$(npm pkg get version | sed 's/\"//g')
          git checkout -b release/v$VERSION
          git push --set-upstream origin release/v$VERSION

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'release/') }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Tag
        run: |
          VERSION=$(echo $REF | rev | cut -d '/' -f 1 | rev)
          git tag -a $VERSION
          git push --follow-tags
